-- Mercado Mayorista — redacción v3 (criterio de evaluación real).
-- Generado por _genReemplazoItems.js. UNA sola sentencia: atómica, y todos los
-- CTEs leen el mismo snapshot, así que el respaldo captura el estado PREVIO.
WITH nuevos (id, id_protocolo, partida_item, descripcion, metodo, seccion) AS (
  VALUES
    ('bpUIeBVCZHz8FMwC', 'CTTR', '1', '¿El trazo lo ejecutó un topógrafo calificado?', 'Verificación documental', 'TRAZO INICIAL'),
    ('Z6b9DGH1LBIRloig', 'CTTR', '2', '¿El terreno fue liberado y entregado para iniciar el trazo?', 'Verificación documental', 'TRAZO INICIAL'),
    ('WmdODJ2pM7PQ2tb8', 'CTTR', '3', '¿Se verificaron el alineamiento, las medidas y la escuadra del trazo?', 'Medición topográfica', 'TRAZO INICIAL'),
    ('4M68vrEh1T2Ecs5s', 'CTTR', '4', '¿El trazo coincide con el plano base, sin modificaciones? (de haberlas, detallarlas en observaciones)', 'Verificación contra plano', 'TRAZO INICIAL'),
    ('8d8qA3LRzoKWS0vU', 'CTTR', '5', '¿Las dimensiones replanteadas de la estructura coinciden con el plano?', 'Medición topográfica', 'TRAZO REPLANTEADO'),
    ('hgSDXoWpsvL5PkLH', 'CTTR', '6', '¿Se materializaron en campo los vértices de la estructura?', 'Medición topográfica', 'TRAZO REPLANTEADO'),
    ('zE7U5ZCMjPAXtffo', 'CTTR', '7', '¿El trazo final de la estructura quedó marcado y verificado?', 'Medición topográfica', 'TRAZO REPLANTEADO'),
    ('N0ErSa664xFrtLqv', 'CTTR', '8', '¿El equipo topográfico cuenta con certificado de calibración vigente?', 'Verificación documental', 'TRAZO REPLANTEADO'),
    ('AsSVix9M4qBtf0uo', 'CTPT', '1', '¿El levantamiento lo ejecutó un topógrafo calificado?', 'Verificación documental', 'TRAZO INICIAL'),
    ('cct7K4xWcdt4NYCL', 'CTPT', '2', '¿El terreno fue liberado y entregado para iniciar el levantamiento?', 'Verificación documental', 'TRAZO INICIAL'),
    ('WYhf2QmxJd7cDRxU', 'CTPT', '3', '¿Se verificaron el alineamiento, las medidas y la escuadra del levantamiento?', 'Medición topográfica', 'TRAZO INICIAL'),
    ('O9qiQMeLzZhWD9q5', 'CTPT', '4', '¿El levantamiento coincide con el plano base, sin modificaciones? (de haberlas, detallarlas en observaciones)', 'Verificación contra plano', 'TRAZO INICIAL'),
    ('NujAAvNeT2JbkmVh', 'CTPT', '5', '¿Las dimensiones levantadas de la estructura coinciden con el plano?', 'Medición topográfica', 'TRAZO REPLANTEADO'),
    ('7MefbFei2YvNEUuk', 'CTPT', '6', '¿Se materializaron en campo los vértices de la estructura?', 'Medición topográfica', 'TRAZO REPLANTEADO'),
    ('RBVCEkccZ3LeLAk8', 'CTPT', '7', '¿El trazo final de la estructura quedó marcado y verificado?', 'Medición topográfica', 'TRAZO REPLANTEADO'),
    ('DkXMElFKZWqMfGfq', 'CTPT', '8', '¿Los espacios levantados quedaron señalizados en campo?', 'Inspección visual', 'TRAZO REPLANTEADO'),
    ('aFgHrdEmcOaEHlwb', 'LIPMPP', '1', 'Diámetro de pernos de anclaje', 'list-[3/8", 5/8", 3/4"]', 'DATOS DEL ELEMENTO Y EQUIPO'),
    ('D9IEpkK4k25IaavX', 'LIPMPP', '2', 'Equipo topográfico utilizado', 'texto-[]', 'DATOS DEL ELEMENTO Y EQUIPO'),
    ('LqyQspB1gaJLsOCT', 'LIPMPP', '3', 'N° de serie del equipo', 'texto-[]', 'DATOS DEL ELEMENTO Y EQUIPO'),
    ('bah6QUShRwf0HKKA', 'LIPMPP', '4', 'Fecha de calibración del equipo', 'fecha-[]', 'DATOS DEL ELEMENTO Y EQUIPO'),
    ('oRIG9xfNvGZEFfWx', 'LIPMPP', '5', '¿La base de la plancha metálica está correctamente ejecutada?', 'list-[CONFORME, OBSERVADO, N/A]', 'CHECK LIST — INSTALACIÓN DE PLANCHAS Y PERNOS'),
    ('0MdtvRr45ySkVclv', 'LIPMPP', '6', '¿Los pernos de anclaje tienen la longitud y el diámetro especificados?', 'list-[CONFORME, OBSERVADO, N/A]', 'CHECK LIST — INSTALACIÓN DE PLANCHAS Y PERNOS'),
    ('Om0ByTHZ51lUhROD', 'LIPMPP', '7', '¿La plancha metálica está alineada según el plano?', 'list-[CONFORME, OBSERVADO, N/A]', 'CHECK LIST — INSTALACIÓN DE PLANCHAS Y PERNOS'),
    ('Nxlye1aqeyFne61U', 'LIPMPP', '8', '¿La plancha metálica y los pernos están nivelados?', 'list-[CONFORME, OBSERVADO, N/A]', 'CHECK LIST — INSTALACIÓN DE PLANCHAS Y PERNOS'),
    ('LusalJRgmCRR5mAr', 'LIPMPP', '9', '¿La plancha y los pernos de anclaje guardan el alineamiento entre sí?', 'list-[CONFORME, OBSERVADO, N/A]', 'CHECK LIST — INSTALACIÓN DE PLANCHAS Y PERNOS'),
    ('qEMLZLvbjUWwimFD', 'LIPMPP', '10', 'col-[A][Eje / Elemento] // col-[B][Norte (plano)] // col-[C][Este (plano)] // col-[D][Z (plano)] // col-[E][Norte (campo)] // col-[F][Este (campo)] // col-[G][Z (campo)] // col-[H][Var. Norte (m)] // col-[I][Var. Este (m)] // col-[J][Var. Z (m)] // col-[K][Dentro de tolerancia (1=Sí)]', '', 'CONTROL DE COORDENADAS'),
    ('bdhKYkaRDJdQ2XjH', 'LIPMPP', '11', 'Detalle 1', 'texto-[] // numerico-[]:dec[3]:ej[8674250.000] // numerico-[]:dec[3]:ej[476320.000] // numerico-[]:dec[3]:ej[3260.000] // numerico-[]:dec[3]:ej[8674250.008] // numerico-[]:dec[3]:ej[476320.006] // numerico-[]:dec[3]:ej[3260.004] // numerico-fx[#11E-#11B]:dec[3] // numerico-fx[#11F-#11C]:dec[3] // numerico-fx[#11G-#11D]:dec[3] // numerico-fx[SI(Y(ABS(#11H)<=0.02, ABS(#11I)<=0.02, ABS(#11J)<=0.02), 1, 0)]:dec[0]', 'CONTROL DE COORDENADAS'),
    ('FpzgWLxzxHnjqwP7', 'LIPMPP', '12', 'Detalle 2', 'texto-[] // numerico-[]:dec[3]:ej[8674250.000] // numerico-[]:dec[3]:ej[476320.000] // numerico-[]:dec[3]:ej[3260.000] // numerico-[]:dec[3]:ej[8674250.008] // numerico-[]:dec[3]:ej[476320.006] // numerico-[]:dec[3]:ej[3260.004] // numerico-fx[#12E-#12B]:dec[3] // numerico-fx[#12F-#12C]:dec[3] // numerico-fx[#12G-#12D]:dec[3] // numerico-fx[SI(Y(ABS(#12H)<=0.02, ABS(#12I)<=0.02, ABS(#12J)<=0.02), 1, 0)]:dec[0]', 'CONTROL DE COORDENADAS'),
    ('fh1gMLci65BbgYvd', 'LIPMPP', '13', 'Detalle 3', 'texto-[] // numerico-[]:dec[3]:ej[8674250.000] // numerico-[]:dec[3]:ej[476320.000] // numerico-[]:dec[3]:ej[3260.000] // numerico-[]:dec[3]:ej[8674250.008] // numerico-[]:dec[3]:ej[476320.006] // numerico-[]:dec[3]:ej[3260.004] // numerico-fx[#13E-#13B]:dec[3] // numerico-fx[#13F-#13C]:dec[3] // numerico-fx[#13G-#13D]:dec[3] // numerico-fx[SI(Y(ABS(#13H)<=0.02, ABS(#13I)<=0.02, ABS(#13J)<=0.02), 1, 0)]:dec[0]', 'CONTROL DE COORDENADAS'),
    ('wELw5Zc3UjIAMeSh', 'LIPMPP', '14', 'Detalle 4', 'texto-[] // numerico-[]:dec[3]:ej[8674250.000] // numerico-[]:dec[3]:ej[476320.000] // numerico-[]:dec[3]:ej[3260.000] // numerico-[]:dec[3]:ej[8674250.008] // numerico-[]:dec[3]:ej[476320.006] // numerico-[]:dec[3]:ej[3260.004] // numerico-fx[#14E-#14B]:dec[3] // numerico-fx[#14F-#14C]:dec[3] // numerico-fx[#14G-#14D]:dec[3] // numerico-fx[SI(Y(ABS(#14H)<=0.02, ABS(#14I)<=0.02, ABS(#14J)<=0.02), 1, 0)]:dec[0]', 'CONTROL DE COORDENADAS'),
    ('4RsfJubPfnn0cbXe', 'LIPMPP', '15', 'Detalle 5', 'texto-[] // numerico-[]:dec[3]:ej[8674250.000] // numerico-[]:dec[3]:ej[476320.000] // numerico-[]:dec[3]:ej[3260.000] // numerico-[]:dec[3]:ej[8674250.008] // numerico-[]:dec[3]:ej[476320.006] // numerico-[]:dec[3]:ej[3260.004] // numerico-fx[#15E-#15B]:dec[3] // numerico-fx[#15F-#15C]:dec[3] // numerico-fx[#15G-#15D]:dec[3] // numerico-fx[SI(Y(ABS(#15H)<=0.02, ABS(#15I)<=0.02, ABS(#15J)<=0.02), 1, 0)]:dec[0]', 'CONTROL DE COORDENADAS'),
    ('oZykEpOVvLGQ1ESV', 'PA', '1', '¿El acero cuenta con certificado de calidad del lote y corresponde al grado especificado? (grado y diámetro trazables a la colada)', 'Verificación documental', 'INSPECCIÓN'),
    ('EqCy2pPOA9vDUeL2', 'PA', '2', '¿El procedimiento de habilitación y colocación vigente está disponible en el frente y el personal fue instruido en él?', 'Verificación documental', 'INSPECCIÓN'),
    ('EHGmLMYdjNComaw3', 'PA', '3', '¿Se contrastaron los planos de las tres especialidades y NO quedan interferencias sin resolver? (listarlas en observaciones)', 'Verificación contra plano', 'INSPECCIÓN'),
    ('1eX1nre9ER5eepam', 'PA', '4', '¿Los ejes y niveles del elemento fueron verificados topográficamente, con desviación dentro de ±10 mm respecto al plano?', 'Medición topográfica', 'INSPECCIÓN'),
    ('f02kqxNsCGMljcRB', 'PA', '5', '¿Los diámetros de las barras coinciden con el plano, verificados por marca de laminado o calibrador en al menos 3 barras por lecho?', 'Medición en campo', 'INSPECCIÓN'),
    ('ZvJZBi0IIrzAJbYF', 'PA', '6', '¿La cantidad de barras es EXACTAMENTE la del plano y el espaciamiento no se desvía más de ±2 cm?', 'Medición en campo', 'INSPECCIÓN'),
    ('OlVIkozgphydyB6v', 'PA', '7', '¿Los traslapes cumplen la longitud indicada en el plano?', 'Medición en campo', 'INSPECCIÓN'),
    ('0LBHZ5OLVUH3lz0I', 'PA', '8', '¿NINGÚN traslape cae en zona de confinamiento ni donde el plano lo prohíbe? (RNE E.060 — cumplir la longitud no basta si está en la zona de máximo esfuerzo)', 'Verificación contra plano', 'INSPECCIÓN'),
    ('WAHAwEBu9ZVkC7sJ', 'PA', '9', '¿El espaciamiento de estribos cumple ±2 cm y la longitud de la zona de confinamiento coincide con el detalle? (RNE E.060)', 'Medición en campo', 'INSPECCIÓN'),
    ('IaIROLYNPfS7BWUD', 'PA', '10', '¿El recubrimiento está garantizado con dados o separadores del espesor especificado, en cantidad suficiente para que la armadura no ceda durante el vaciado?', 'Medición en campo', 'INSPECCIÓN'),
    ('oCzx87iHM9Zc0KPs', 'PA', '11', '¿Las armaduras están ancladas, fijadas y arriostradas de modo que no se desplacen durante el vaciado y el vibrado?', 'Inspección visual', 'INSPECCIÓN'),
    ('vSjhEdPtNldm3Lfq', 'PA', '12', '¿Las barras están libres de óxido no adherente, grasa, aceite, pintura o lechada que reduzcan la adherencia con el concreto?', 'Inspección visual', 'INSPECCIÓN'),
    ('TEZKZx7JHU0xNVSQ', 'PA', '13', '¿El frente cuenta con las protecciones colectivas requeridas y las esperas verticales están tapadas? (líneas de vida, plataformas, barandas y tapas antiempalamiento)', 'Inspección visual', 'INSPECCIÓN'),
    ('rul9FjMszrCCDw49', 'PCC', '1', '¿El procedimiento de vaciado está definido para este elemento, incluyendo qué hacer ante lluvia, falla de bomba o junta fría no prevista?', 'list-[SI, NO, NA]', 'INSPECCIÓN PREVIA AL VACIADO'),
    ('G74iKWoLKRcLFiGo', 'PCC', '2', '¿Los niveles de vaciado están marcados en el elemento y verificados topográficamente?', 'list-[SI, NO, NA]', 'INSPECCIÓN PREVIA AL VACIADO'),
    ('4ZHqhn5w9iwkc8Z2', 'PCC', '3', '¿Las juntas de construcción están en la ubicación prevista, con la superficie rugosa, limpia y saturada pero sin agua libre?', 'list-[SI, NO, NA]', 'INSPECCIÓN PREVIA AL VACIADO'),
    ('W693qE8ce8lbBDED', 'PCC', '4', '¿El acero de refuerzo está LIBERADO con su protocolo aprobado?', 'list-[SI, NO, NA]', 'INSPECCIÓN PREVIA AL VACIADO'),
    ('PhpgYsDQrlJzkfC7', 'PCC', '5', '¿El encofrado está LIBERADO con su protocolo aprobado?', 'list-[SI, NO, NA]', 'INSPECCIÓN PREVIA AL VACIADO'),
    ('nlwikZvBRj4uhZJd', 'PCC', '6', '¿Las instalaciones sanitarias embebidas están liberadas, tapadas y aseguradas para que no se desplacen durante el vaciado?', 'list-[SI, NO, NA]', 'INSPECCIÓN PREVIA AL VACIADO'),
    ('lREvQ83ZzipPPeiF', 'PCC', '7', '¿Las instalaciones eléctricas embebidas están liberadas, con guía y tapadas para que no se llenen de concreto?', 'list-[SI, NO, NA]', 'INSPECCIÓN PREVIA AL VACIADO'),
    ('eZF4dj6zJYXvboeI', 'PCC', '8', '¿Las instalaciones mecánicas embebidas están liberadas y aseguradas?', 'list-[SI, NO, NA]', 'INSPECCIÓN PREVIA AL VACIADO'),
    ('6HKTAzzsouBwgQmI', 'PCC', '9', '¿Los anclajes para estructuras metálicas están en posición, con plantilla y nivel verificados?', 'list-[SI, NO, NA]', 'INSPECCIÓN PREVIA AL VACIADO'),
    ('GP8GmoUwcH70H4Mj', 'PCC', '10', '¿El equipo de vaciado está operativo y se cuenta con vibrador de RESERVA en el frente? (una falla a media losa deja cangrejeras)', 'list-[SI, NO, NA]', 'INSPECCIÓN PREVIA AL VACIADO'),
    ('oYQlnksa1JK1Agun', 'PCC', '11', '¿Las condiciones de clima y temperatura permiten vaciar según especificación, y se previó el manejo si cambian?', 'list-[SI, NO, NA]', 'INSPECCIÓN PREVIA AL VACIADO'),
    ('TgRr6lBTXoz3wZI1', 'PCC', '12', 'N° de batch', 'texto-[]', 'DATOS DE LA COLOCACIÓN'),
    ('lmENfcZBfwcFlJk2', 'PCC', '13', 'Tipo de concreto', 'list-[HECHO EN OBRA, PREMEZCLADO]', 'DATOS DE LA COLOCACIÓN'),
    ('CWldVz9TPcyqo9Gs', 'PCC', '14', 'f''c de diseño (kg/cm²)', 'numerico-[100:700]:dec[0]', 'DATOS DE LA COLOCACIÓN'),
    ('v9qEReqdQAfjKtfY', 'PCC', '15', 'Slump de diseño (pulg)', 'numerico-[1:10]:dec[1]', 'DATOS DE LA COLOCACIÓN'),
    ('LVeunOJhH4J5aHGb', 'PCC', '16', 'Volumen total (m³)', 'numerico-[0:500]:dec[2]', 'DATOS DE LA COLOCACIÓN'),
    ('DVoerAXiqq8iDQE1', 'PCC', '17', 'Tipo de colocación', 'list-[DIRECTO, CON BOMBA, OTROS]', 'DATOS DE LA COLOCACIÓN'),
    ('cVN29TBWbMz7pBDy', 'PCC', '18', 'Tipo de acabado', 'list-[CARAVISTA, FROTACHADO, OTROS]', 'DATOS DE LA COLOCACIÓN'),
    ('0beZM5W3qVWPCPfe', 'PCC', '19', 'col-[A][Guía / Batch] // col-[B][Hora mezclado] // col-[C][Hora colocación] // col-[D][Slump (pulg)] // col-[E][Temp. (°C)] // col-[F][Volumen (m³)] // col-[G][Código de testigos]', '', 'REGISTRO DE BATCHES'),
    ('iEzBPXyn2VLm4tpA', 'PCC', '20', 'Batch 1', 'texto-[] // hora-[] // hora-[] // numerico-[1:10]:dec[1] // numerico-[5:40]:dec[1] // numerico-[0:100]:dec[2] // texto-[]', 'REGISTRO DE BATCHES'),
    ('dLh1v6DGAW5lJxpQ', 'PCC', '21', 'Batch 2', 'texto-[] // hora-[] // hora-[] // numerico-[1:10]:dec[1] // numerico-[5:40]:dec[1] // numerico-[0:100]:dec[2] // texto-[]', 'REGISTRO DE BATCHES'),
    ('Nc9nz9ECF0Yzl6AC', 'PCC', '22', 'Batch 3', 'texto-[] // hora-[] // hora-[] // numerico-[1:10]:dec[1] // numerico-[5:40]:dec[1] // numerico-[0:100]:dec[2] // texto-[]', 'REGISTRO DE BATCHES'),
    ('TOFELirnmSJW6Uhx', 'PCC', '23', 'Batch 4', 'texto-[] // hora-[] // hora-[] // numerico-[1:10]:dec[1] // numerico-[5:40]:dec[1] // numerico-[0:100]:dec[2] // texto-[]', 'REGISTRO DE BATCHES'),
    ('KrFeaad9HjXNOog5', 'PCC', '24', 'Batch 5', 'texto-[] // hora-[] // hora-[] // numerico-[1:10]:dec[1] // numerico-[5:40]:dec[1] // numerico-[0:100]:dec[2] // texto-[]', 'REGISTRO DE BATCHES'),
    ('gH1iJIAIx6FWH20U', 'PCC', '25', 'Batch 6', 'texto-[] // hora-[] // hora-[] // numerico-[1:10]:dec[1] // numerico-[5:40]:dec[1] // numerico-[0:100]:dec[2] // texto-[]', 'REGISTRO DE BATCHES'),
    ('CcsADnkkmxTdZwmd', 'PCC', '26', 'Volumen total colocado (m³)', 'numerico-fx[SUMA(#20E:#25E)]:dec[2]', 'REGISTRO DE BATCHES'),
    ('v7BN0rf28iZvWnpN', 'PCC', '27', '¿Se tomaron las probetas según norma (un juego por cada 50 m³ o fracción, mínimo uno por día de vaciado), identificadas y protegidas en obra? (NTP 339.033)', 'list-[SI, NO, NA]', 'INSPECCIÓN POSTERIOR AL VACIADO'),
    ('Bw82Hjz2EDEv6pOR', 'PCC', '28', '¿El slump de cada batch se mantuvo dentro de la tolerancia del diseño y se rechazó el que no cumplía? (registrar rechazos en observaciones)', 'list-[SI, NO, NA]', 'INSPECCIÓN POSTERIOR AL VACIADO'),
    ('Hek2aOh3eCd4X7bX', 'PCC', '29', '¿El acabado superficial corresponde al especificado y está libre de cangrejeras, segregación o juntas frías? (describir y ubicar cualquier defecto en observaciones)', 'list-[SI, NO, NA]', 'INSPECCIÓN POSTERIOR AL VACIADO'),
    ('nyUU62e3UXFIKH5j', 'PCC', '30', '¿El desplome del elemento terminado es menor a 6 mm por cada 3 m de altura y los niveles cumplen ±10 mm?', 'list-[SI, NO, NA]', 'INSPECCIÓN POSTERIOR AL VACIADO'),
    ('btkxS7tXPyi7VEsG', 'PCC', '31', '¿Los elementos embebidos quedaron en su posición final, sin desplazamiento respecto al plano?', 'list-[SI, NO, NA]', 'INSPECCIÓN POSTERIOR AL VACIADO'),
    ('NBP7v8hlhuBGnAAP', 'PCC', '32', '¿El curado se inició apenas el acabado lo permitió y se mantendrá al menos 7 días? (RNE E.060 — sin curado no se alcanza el f''c)', 'list-[SI, NO, NA]', 'INSPECCIÓN POSTERIOR AL VACIADO'),
    ('qAGNfCkOCY33ZDkm', 'PCC', '33', '¿El área quedó ordenada y los residuos de concreto se retiraron antes de fraguar?', 'list-[SI, NO, NA]', 'INSPECCIÓN POSTERIOR AL VACIADO'),
    ('xuN6TaxmMej631So', 'PE', '1', '¿El diseño del encofrado y del apuntalamiento está aprobado y disponible en el frente, para las cargas de este elemento?', 'Verificación documental', 'INSPECCIÓN'),
    ('2kDym9DmpwbQgTcR', 'PE', '2', '¿El trazo y los niveles del encofrado fueron verificados topográficamente, con desviación dentro de ±10 mm?', 'Medición topográfica', 'INSPECCIÓN'),
    ('kOM033R3v2x89ud8', 'PE', '3', '¿El desplome del encofrado es menor a 6 mm por cada 3 m de altura y no hay paneles alabeados ni deformados?', 'Medición en campo', 'INSPECCIÓN'),
    ('wyoarRb3NCqvHhVC', 'PE', '4', '¿Las dimensiones internas están dentro de la tolerancia de la sección? (+12 mm / −6 mm respecto al plano)', 'Medición en campo', 'INSPECCIÓN'),
    ('IbjgyRSEfBgpv0g4', 'PE', '5', '¿El apuntalamiento está completo, arriostrado y apoyado sobre superficie firme y nivelada, capaz de resistir el concreto fresco sin asentarse?', 'Inspección visual', 'INSPECCIÓN'),
    ('0qJ8j9n2g3TjY8uM', 'PE', '6', '¿Las juntas y encuentros del encofrado están sellados de modo que no se fugue lechada durante el vaciado?', 'Inspección visual', 'INSPECCIÓN'),
    ('XZ37P6I0v60C6Nv8', 'PE', '7', '¿Los separadores laterales mantienen la armadura a la distancia correcta de la cara del encofrado en toda la altura?', 'Medición en campo', 'INSPECCIÓN'),
    ('tf4j30LL6DjHVDBZ', 'PE', '8', '¿El interior del encofrado está libre de recortes, alambres, aserrín y agua empozada?', 'Inspección visual', 'INSPECCIÓN'),
    ('PNNvFEj8yLBTPhDj', 'PE', '9', '¿El desmoldante se aplicó ANTES de montar la armadura, o sin contaminarla? (el desmoldante sobre las barras anula la adherencia con el concreto)', 'Inspección visual', 'INSPECCIÓN'),
    ('aMvr9hnAtjKyvEOn', 'PE', '10', '¿Los pases y tubos de instalaciones sanitarias están según plano y fijados para no desplazarse durante el vaciado?', 'Verificación contra plano', 'INSPECCIÓN'),
    ('6CVOwVjkDPSRQHBc', 'PE', '11', '¿Los pases y tubos de instalaciones eléctricas están según plano y fijados para no desplazarse durante el vaciado?', 'Verificación contra plano', 'INSPECCIÓN'),
    ('bbtNm28hUAFREDUU', 'PE', '12', '¿Los soportes y anclajes para instalaciones y estructuras metálicas están en su posición final y asegurados?', 'Verificación contra plano', 'INSPECCIÓN'),
    ('UGtcG3v51Lr0xkVM', 'PE', '13', '¿Está definido el plazo mínimo de desencofrado para este elemento y comunicado al personal? (evita el desencofrado prematuro)', 'Verificación documental', 'INSPECCIÓN'),
    ('p0wWFQVAS27qDWlZ', 'PE', '14', '¿El frente cuenta con accesos seguros, barandas y protección de bordes, y la zona bajo el encofrado está señalizada?', 'Inspección visual', 'INSPECCIÓN'),
    ('uBrkVLS3fiIlU1nP', 'PAA', '1', '¿La varilla quedó alineada y centrada en su posición definitiva?', 'Medición topográfica', 'INSPECCIÓN'),
    ('U7iQVFdnqYqavFnd', 'PAA', '2', '¿Se respetó el recubrimiento mínimo de 2 cm respecto al borde del concreto?', 'Medición en campo', 'INSPECCIÓN'),
    ('XL7bC4ljqZcZPkdl', 'PAA', '3', '¿La perforación se ejecutó con rotomartillo y broca de carburo para concreto?', 'Inspección visual', 'INSPECCIÓN'),
    ('rwtDLT8ZmtQ8FyJd', 'PAA', '4', '¿El diámetro de la perforación es mayor que el de la varilla, según la ficha técnica del anclaje?', 'Medición en campo', 'INSPECCIÓN'),
    ('bUXaIDBQwSKTdrh2', 'PAA', '5', '¿La perforación alcanza al menos 200 mm de profundidad en el concreto estructural?', 'Medición en campo', 'INSPECCIÓN'),
    ('mfE1icWwUxjXwmsh', 'PAA', '6', '¿Se limpió la perforación con aire comprimido y escobilla antes de inyectar?', 'Inspección visual', 'INSPECCIÓN'),
    ('KzOYyzAhY7Td92kk', 'PAA', '7', '¿El adhesivo se inyectó desde el fondo hasta dos tercios del volumen de la perforación?', 'Inspección visual', 'INSPECCIÓN'),
    ('GCoanDcinDOywGvX', 'PAA', '8', '¿La varilla se insertó girando hasta el fondo, cubriendo todo el corrugado con resina?', 'Inspección visual', 'INSPECCIÓN'),
    ('FEVBro7vMe8ljnW5', 'PAA', '9', '¿Se respetó el tiempo de curado según la temperatura ambiente? (20 °C: 24 h · 10 °C: 48 h · menos de 5 °C: 72 h)', 'Verificación documental', 'INSPECCIÓN'),
    ('AQ5e9nZfHyfEwVyQ', 'PAA', '10', 'undefined', 'Inspección visual', 'INSPECCIÓN'),
    ('ePHLYNXKxXbeQo99', 'PIS', '1', '¿Las tuberías y accesorios siguen el trazo del plano y los diámetros coinciden, verificados tramo por tramo?', 'Verificación contra plano', 'DESCRIPCIÓN DE ACTIVIDADES'),
    ('iBVeokYWGLBpGRKN', 'PIS', '2', '¿El material y la clase corresponden a lo especificado, con marcado de fabricante y clase legible en la tubería?', 'Verificación documental', 'DESCRIPCIÓN DE ACTIVIDADES'),
    ('DYRkqyw82QV41ohv', 'PIS', '3', '¿El material está libre de fisuras, deformaciones por calor o golpes que comprometan la estanqueidad?', 'Inspección visual', 'DESCRIPCIÓN DE ACTIVIDADES'),
    ('JivZJNFq8EJsLun5', 'PIS', '4', '¿La pendiente de los tramos de desagüe cumple el mínimo especificado (≥ 1 %), verificada con nivel en cada tramo?', 'Medición en campo', 'DESCRIPCIÓN DE ACTIVIDADES'),
    ('h8ceYwlpg3VD7Day', 'PIS', '5', '¿Las uniones se ejecutaron con la técnica y el pegamento especificados, respetando el tiempo de fraguado antes de probar?', 'Inspección visual', 'DESCRIPCIÓN DE ACTIVIDADES'),
    ('WuugHdTzCdlOwM8r', 'PIS', '6', '¿Se ejecutó la prueba de estanqueidad del tramo y se mantuvo SIN pérdida durante el tiempo especificado? (registrar resultado en observaciones)', 'Prueba de funcionamiento', 'DESCRIPCIÓN DE ACTIVIDADES'),
    ('uJtno0UuuZwNEhOO', 'PIS', '7', '¿Los soportes están al espaciamiento especificado y sujetan la tubería sin deformarla ni impedir su dilatación?', 'Inspección visual', 'DESCRIPCIÓN DE ACTIVIDADES'),
    ('gAX68dlAijgXZnOK', 'PIS', '8', '¿Los terminales expuestos y las cajas de paso quedaron taponeados para impedir el ingreso de concreto o residuos?', 'Inspección visual', 'DESCRIPCIÓN DE ACTIVIDADES'),
    ('YRmLEL1OnL0UZqg8', 'PIE', '1', '¿Los puntos están en la ubicación del plano, con desviación menor a 2 cm respecto al eje de referencia?', 'Verificación contra plano', 'DESCRIPCIÓN DE ACTIVIDADES'),
    ('Ba9y1uysHeMjXsF6', 'PIE', '2', '¿El diámetro de la tubería corresponde al plano y el material y clase son los especificados?', 'Medición en campo', 'DESCRIPCIÓN DE ACTIVIDADES'),
    ('tjz8Fi97ddmTMtfb', 'PIE', '3', '¿Las tuberías están libres de aplastamientos y roturas, y los radios de curvatura son mayores a 6 veces el diámetro? (curvas cerradas impiden el cableado)', 'Medición en campo', 'DESCRIPCIÓN DE ACTIVIDADES'),
    ('9jb0jlybxr0C4i8p', 'PIE', '4', '¿Los accesorios son del mismo material y clase que la tubería, con marcado legible? (uniones, conectores y curvas)', 'Inspección visual', 'DESCRIPCIÓN DE ACTIVIDADES'),
    ('SQpRWJF1UCdkXfee', 'PIE', '5', '¿Las cajas están en el trazo y a la altura especificada, con desviación menor a ±2 cm? (octogonales, rectangulares y de paso)', 'Medición topográfica', 'DESCRIPCIÓN DE ACTIVIDADES'),
    ('sKXxu1diFMgiaDAW', 'PIE', '6', '¿Los soportes están al espaciamiento especificado y sujetan la tubería sin deformarla ni impedir su dilatación?', 'Inspección visual', 'DESCRIPCIÓN DE ACTIVIDADES'),
    ('UkiKBvdU6TRabWii', 'PIE', '7', '¿Los ductos quedaron con alambre guía y los extremos tapados, y se verificó que pasa la guía entre cajas?', 'Prueba de funcionamiento', 'DESCRIPCIÓN DE ACTIVIDADES'),
    ('H1V6StcmvgZ1aqjM', 'PIE', '8', '¿Las tuberías y accesorios están en buen estado, sin tramos expuestos a golpes durante el vaciado?', 'Inspección visual', 'DESCRIPCIÓN DE ACTIVIDADES'),
    ('198Rfw8heOv5K0qf', 'PIE', '9', '¿El área quedó libre de residuos, recortes y material sobrante que puedan obstruir el trabajo posterior?', 'Inspección visual', 'DESCRIPCIÓN DE ACTIVIDADES'),
    ('sjmLBNB5L2akYNoP', 'PPIS', '1', '¿La red instalada corresponde al tipo previsto y está diferenciada en obra? (agua fría / agua caliente)', 'Verificación contra plano', 'VERIFICACIÓN PUNTOS DE AGUA'),
    ('WQhIuDaoMxYo4MTc', 'PPIS', '2', '¿El material y la clase de la red son los especificados? (PVC, PPR o acero, con marcado legible)', 'Verificación documental', 'VERIFICACIÓN PUNTOS DE AGUA'),
    ('gVpH0xOqtIRJGjMX', 'PPIS', '3', '¿Los puntos de agua están en la ubicación y a la ALTURA del plano, con desviación menor a ±2 cm?', 'Medición en campo', 'VERIFICACIÓN PUNTOS DE AGUA'),
    ('XVfOQ1c8nWDrzx9U', 'PPIS', '4', '¿La cantidad de puntos de salida es EXACTAMENTE la del plano? (un punto de menos obliga a picar después)', 'Medición en campo', 'VERIFICACIÓN PUNTOS DE AGUA'),
    ('BxoUZnKCyhlafPQM', 'PPIS', '5', '¿El diámetro y el recorrido de la tubería corresponden al plano, sin reducciones ni desvíos no autorizados?', 'Medición en campo', 'VERIFICACIÓN PUNTOS DE AGUA'),
    ('rr4IZ5BqCfrn2CwZ', 'PPIS', '6', '¿El tipo y la separación entre salidas corresponden al aparato previsto, medida entre ejes? (ovalín, inodoro, urinario u otro)', 'Medición en campo', 'VERIFICACIÓN PUNTOS DE AGUA'),
    ('eL5TzsWV5JXIjz0X', 'PPIS', '7', '¿Se instaló la válvula de paso donde indica el plano y queda accesible para mantenimiento?', 'Inspección visual', 'VERIFICACIÓN PUNTOS DE AGUA'),
    ('Crhjvc2A0FCSKx1L', 'PPIS', '8', '¿El tramo pasó la prueba de presión sin pérdida durante el tiempo especificado? (registrar valor en observaciones)', 'Prueba de funcionamiento', 'VERIFICACIÓN PUNTOS DE AGUA'),
    ('8YDtnOCwpxBJFcHk', 'PPIS', '9', '¿El área quedó libre de residuos, recortes y material sobrante que puedan obstruir el trabajo posterior?', 'Inspección visual', 'VERIFICACIÓN PUNTOS DE AGUA'),
    ('F75C46kyDBIJok6v', 'PPIS', '10', '¿Los puntos de desagüe están en la ubicación y a la ALTURA del plano, con desviación menor a ±2 cm?', 'Medición en campo', 'VERIFICACIÓN PUNTOS DE DESAGÜE'),
    ('ZyGh4QXKNZQHTVS2', 'PPIS', '11', '¿El material y la clase de la red son los especificados? (PVC o PPR, con marcado legible)', 'Verificación documental', 'VERIFICACIÓN PUNTOS DE DESAGÜE'),
    ('jFAkbJNoC6RsF5Ec', 'PPIS', '12', '¿La cantidad de puntos de salida es EXACTAMENTE la del plano? (un punto de menos obliga a picar después)', 'Medición en campo', 'VERIFICACIÓN PUNTOS DE DESAGÜE'),
    ('WzpLKbLVy2iFBKhr', 'PPIS', '13', '¿El diámetro y el recorrido de la tubería corresponden al plano, sin reducciones ni desvíos no autorizados?', 'Medición en campo', 'VERIFICACIÓN PUNTOS DE DESAGÜE'),
    ('qAtzDtAItu7mfQi4', 'PPIS', '14', '¿La pendiente de los ramales cumple el mínimo especificado (≥ 1 %), verificada con nivel?', 'Medición en campo', 'VERIFICACIÓN PUNTOS DE DESAGÜE'),
    ('2sJEJIz33lRn2h75', 'PPIS', '15', '¿El tipo de salida corresponde al aparato previsto? (ovalín, inodoro u otro)', 'Inspección visual', 'VERIFICACIÓN PUNTOS DE DESAGÜE'),
    ('R3RlieOotrRiRmHE', 'PPIS', '16', '¿Se instalaron los puntos de urinario, registro y sumidero previstos, y los registros quedan accesibles?', 'Inspección visual', 'VERIFICACIÓN PUNTOS DE DESAGÜE'),
    ('TJpMzLrBvTN9yP3b', 'PPIS', '17', '¿El tramo pasó la prueba de estanqueidad sin pérdida durante el tiempo especificado?', 'Prueba de funcionamiento', 'VERIFICACIÓN PUNTOS DE DESAGÜE'),
    ('fwaiHfcvBfIutiFG', 'PPIS', '18', '¿El área quedó libre de residuos, recortes y material sobrante que puedan obstruir el trabajo posterior?', 'Inspección visual', 'VERIFICACIÓN PUNTOS DE DESAGÜE'),
    ('WzTCUxmm4fStrcyt', 'PPIS', '19', '¿Los puntos de ventilación están en la ubicación y altura del plano, con desviación menor a ±2 cm?', 'Medición en campo', 'VERIFICACIÓN PUNTOS DE VENTILACIÓN'),
    ('PJF3OWNT09u5RZui', 'PPIS', '20', '¿El material y la clase de la red son los especificados? (PVC o PPR)', 'Verificación documental', 'VERIFICACIÓN PUNTOS DE VENTILACIÓN'),
    ('3KguuxrYq1t2Rz5i', 'PPIS', '21', '¿La cantidad de puntos de salida es EXACTAMENTE la del plano? (un punto de menos obliga a picar después)', 'Medición en campo', 'VERIFICACIÓN PUNTOS DE VENTILACIÓN'),
    ('KS5YWv8MWvSongzL', 'PPIS', '22', '¿El diámetro y el recorrido de la tubería corresponden al plano, sin reducciones ni desvíos no autorizados?', 'Medición en campo', 'VERIFICACIÓN PUNTOS DE VENTILACIÓN'),
    ('gZ7p5vfGCyJnAzw9', 'PPIS', '23', '¿La ventilación remata según el plano y el recorrido queda libre de obstrucciones o tramos ahogados?', 'Inspección visual', 'VERIFICACIÓN PUNTOS DE VENTILACIÓN'),
    ('2vN9RANKngrE3JlI', 'PPIS', '24', '¿El área quedó libre de residuos, recortes y material sobrante que puedan obstruir el trabajo posterior?', 'Inspección visual', 'VERIFICACIÓN PUNTOS DE VENTILACIÓN'),
    ('BrI1E73FK9c9Jr1z', 'PPIE', '1', '¿La caja equipotencial y las cajas de paso están ubicadas según el plano y quedan accesibles para su medición posterior?', 'Verificación contra plano', 'VERIFICACIÓN SISTEMA DE PUESTA A TIERRA'),
    ('VUp9utgHFLE34FtY', 'PPIE', '2', '¿El diámetro, el recorrido, la caja y la ALTURA corresponden al plano, con desviación menor a ±2 cm?', 'Medición en campo', 'VERIFICACIÓN SISTEMA DE PUESTA A TIERRA'),
    ('mKkkFGsRlkM25bjW', 'PPIE', '3', '¿La cantidad de puntos de salida es EXACTAMENTE la del plano? (un punto de menos obliga a picar después)', 'Medición en campo', 'VERIFICACIÓN SISTEMA DE PUESTA A TIERRA'),
    ('8DchKMKiatCgM2aw', 'PPIE', '4', '¿Los ductos quedaron con alambre guía y los extremos tapados, y se verificó que pasa la guía entre cajas?', 'Prueba de funcionamiento', 'VERIFICACIÓN SISTEMA DE PUESTA A TIERRA'),
    ('MRcvuEnH05NtsfsY', 'PPIE', '5', '¿El área quedó libre de residuos, recortes y material sobrante que puedan obstruir el trabajo posterior?', 'Inspección visual', 'VERIFICACIÓN SISTEMA DE PUESTA A TIERRA'),
    ('PuHhLRUwmx1YW2iW', 'PPIE', '6', '¿Los puntos están en la ubicación del plano, con desviación menor a 2 cm respecto al eje de referencia?', 'Verificación contra plano', 'VERIFICACIÓN PUNTOS DE FUERZA'),
    ('Bd2y78w02efM6Jlo', 'PPIE', '7', '¿El diámetro, el recorrido, la caja y la ALTURA corresponden al plano, con desviación menor a ±2 cm?', 'Medición en campo', 'VERIFICACIÓN PUNTOS DE FUERZA'),
    ('3kZWof8iIcUZENs7', 'PPIE', '8', '¿La cantidad de puntos de salida es EXACTAMENTE la del plano? (un punto de menos obliga a picar después)', 'Medición en campo', 'VERIFICACIÓN PUNTOS DE FUERZA'),
    ('YB6AyAaUbQHnYD08', 'PPIE', '9', '¿Los ductos quedaron con alambre guía y los extremos tapados, y se verificó que pasa la guía entre cajas?', 'Prueba de funcionamiento', 'VERIFICACIÓN PUNTOS DE FUERZA'),
    ('cvv9T23A4fIzrYpv', 'PPIE', '10', '¿El área quedó libre de residuos, recortes y material sobrante que puedan obstruir el trabajo posterior?', 'Inspección visual', 'VERIFICACIÓN PUNTOS DE FUERZA'),
    ('d41upf03z3CI58dk', 'PPIE', '11', '¿Los puntos están en la ubicación del plano, con desviación menor a 2 cm respecto al eje de referencia?', 'Verificación contra plano', 'ALUMBRADO'),
    ('XCnwS0dvD5ouWSml', 'PPIE', '12', '¿El diámetro, el recorrido, la caja y la ALTURA corresponden al plano, con desviación menor a ±2 cm?', 'Medición en campo', 'ALUMBRADO'),
    ('B4kEDz5wLIKKl2GB', 'PPIE', '13', '¿La cantidad de puntos de salida es EXACTAMENTE la del plano? (un punto de menos obliga a picar después)', 'Medición en campo', 'ALUMBRADO'),
    ('Yr9v75H6A4d6j513', 'PPIE', '14', '¿Los ductos quedaron con alambre guía y los extremos tapados, y se verificó que pasa la guía entre cajas?', 'Prueba de funcionamiento', 'ALUMBRADO'),
    ('eGA35F1k1XC0vheP', 'PPIE', '15', '¿El área quedó libre de residuos, recortes y material sobrante que puedan obstruir el trabajo posterior?', 'Inspección visual', 'ALUMBRADO'),
    ('WxAtpEYROnhwAkeL', 'PPIE', '16', '¿Los puntos están en la ubicación del plano, con desviación menor a 2 cm respecto al eje de referencia?', 'Verificación contra plano', 'TOMACORRIENTES'),
    ('xVcRvhA6iEgklmXO', 'PPIE', '17', '¿El diámetro, el recorrido, la caja y la ALTURA corresponden al plano, con desviación menor a ±2 cm?', 'Medición en campo', 'TOMACORRIENTES'),
    ('9TMHvW8iNaMgrcrk', 'PPIE', '18', '¿La cantidad de puntos de salida es EXACTAMENTE la del plano? (un punto de menos obliga a picar después)', 'Medición en campo', 'TOMACORRIENTES'),
    ('fsaDiCWvlY91oQfi', 'PPIE', '19', '¿Los ductos quedaron con alambre guía y los extremos tapados, y se verificó que pasa la guía entre cajas?', 'Prueba de funcionamiento', 'TOMACORRIENTES'),
    ('MT36CzNYXvmHLlHG', 'PPIE', '20', '¿El área quedó libre de residuos, recortes y material sobrante que puedan obstruir el trabajo posterior?', 'Inspección visual', 'TOMACORRIENTES'),
    ('al1HvFGVZwaDdLk5', 'PPIE', '21', '¿Los puntos están en la ubicación del plano, con desviación menor a 2 cm respecto al eje de referencia?', 'Verificación contra plano', 'LUZ DE EMERGENCIA'),
    ('sKOxYaB7wqeomY3q', 'PPIE', '22', '¿El diámetro, el recorrido, la caja y la ALTURA corresponden al plano, con desviación menor a ±2 cm?', 'Medición en campo', 'LUZ DE EMERGENCIA'),
    ('0SRClh3hkF5I0Fr3', 'PPIE', '23', '¿La cantidad de puntos de salida es EXACTAMENTE la del plano? (un punto de menos obliga a picar después)', 'Medición en campo', 'LUZ DE EMERGENCIA'),
    ('dRBb3Lod0rVSyGPk', 'PPIE', '24', '¿Los ductos quedaron con alambre guía y los extremos tapados, y se verificó que pasa la guía entre cajas?', 'Prueba de funcionamiento', 'LUZ DE EMERGENCIA'),
    ('fMv8ncoifD5CNELB', 'PPIE', '25', '¿El área quedó libre de residuos, recortes y material sobrante que puedan obstruir el trabajo posterior?', 'Inspección visual', 'LUZ DE EMERGENCIA'),
    ('Z91q9QxGrXq1WlBG', 'PPIE', '26', '¿Los puntos están ubicados según el plano, con desviación menor a 2 cm? (ACI y plano de intrusión)', 'Verificación contra plano', 'SISTEMA DE ALARMA'),
    ('KnCYbSVVKtgfDW0A', 'PPIE', '27', '¿El diámetro, el recorrido, la caja y la ALTURA corresponden al plano, con desviación menor a ±2 cm?', 'Medición en campo', 'SISTEMA DE ALARMA'),
    ('iBmxZSuzrkWTK1cn', 'PPIE', '28', '¿La cantidad de puntos de salida es EXACTAMENTE la del plano? (un punto de menos obliga a picar después)', 'Medición en campo', 'SISTEMA DE ALARMA'),
    ('GCnu65X1SP9IKw8B', 'PPIE', '29', '¿Los ductos quedaron con alambre guía y los extremos tapados, y se verificó que pasa la guía entre cajas?', 'Prueba de funcionamiento', 'SISTEMA DE ALARMA'),
    ('Qf2mwM9sQ3f2n0YZ', 'PPIE', '30', '¿El área quedó libre de residuos, recortes y material sobrante que puedan obstruir el trabajo posterior?', 'Inspección visual', 'SISTEMA DE ALARMA'),
    ('s5Ofr4Lcwt50m8RJ', 'PPIE', '31', '¿Los puntos están en la ubicación del plano, con desviación menor a 2 cm respecto al eje de referencia?', 'Verificación contra plano', 'SISTEMA DE AIRE ACONDICIONADO'),
    ('yycmtBwOPYE0wtG9', 'PPIE', '32', '¿El diámetro, el recorrido, la caja y la ALTURA corresponden al plano, con desviación menor a ±2 cm?', 'Medición en campo', 'SISTEMA DE AIRE ACONDICIONADO'),
    ('rUTP4xfRkbMFh0Qk', 'PPIE', '33', '¿La cantidad de puntos de salida es EXACTAMENTE la del plano? (un punto de menos obliga a picar después)', 'Medición en campo', 'SISTEMA DE AIRE ACONDICIONADO'),
    ('PSVDjY7mBaotjZBA', 'PPIE', '34', '¿Los ductos quedaron con alambre guía y los extremos tapados, y se verificó que pasa la guía entre cajas?', 'Prueba de funcionamiento', 'SISTEMA DE AIRE ACONDICIONADO'),
    ('7FfSj5ATSyq3UwrP', 'PPIE', '35', '¿El área quedó libre de residuos, recortes y material sobrante que puedan obstruir el trabajo posterior?', 'Inspección visual', 'SISTEMA DE AIRE ACONDICIONADO'),
    ('k1v2rUwvKc6YuJvg', 'PPIE', '36', '¿Los puntos están en la ubicación del plano, con desviación menor a 2 cm respecto al eje de referencia?', 'Verificación contra plano', 'DATA'),
    ('qJ4yDWeLRyYodKVQ', 'PPIE', '37', '¿El diámetro, el recorrido, la caja y la ALTURA corresponden al plano, con desviación menor a ±2 cm?', 'Medición en campo', 'DATA'),
    ('2reWKVNGyoWOj34e', 'PPIE', '38', '¿La cantidad de puntos de salida es EXACTAMENTE la del plano? (un punto de menos obliga a picar después)', 'Medición en campo', 'DATA'),
    ('rMWLCnHZJ0XrORjt', 'PPIE', '39', '¿Los ductos quedaron con alambre guía y los extremos tapados, y se verificó que pasa la guía entre cajas?', 'Prueba de funcionamiento', 'DATA'),
    ('PP4i9AX831Fc03V1', 'PPIE', '40', '¿El área quedó libre de residuos, recortes y material sobrante que puedan obstruir el trabajo posterior?', 'Inspección visual', 'DATA'),
    ('hVqFtSrBU1R8Tham', 'PPIE', '41', '¿Los puntos están en la ubicación del plano, con desviación menor a 2 cm respecto al eje de referencia?', 'Verificación contra plano', 'CIRCUITO CERRADO TV - CCTV'),
    ('QXpK6Vfl5qT6b2Ju', 'PPIE', '42', '¿El diámetro, el recorrido, la caja y la ALTURA corresponden al plano, con desviación menor a ±2 cm?', 'Medición en campo', 'CIRCUITO CERRADO TV - CCTV'),
    ('svh2gaomhuBnxBRX', 'PPIE', '43', '¿La cantidad de puntos de salida es EXACTAMENTE la del plano? (un punto de menos obliga a picar después)', 'Medición en campo', 'CIRCUITO CERRADO TV - CCTV'),
    ('GjpcHuL6q901DwF0', 'PPIE', '44', '¿Los ductos quedaron con alambre guía y los extremos tapados, y se verificó que pasa la guía entre cajas?', 'Prueba de funcionamiento', 'CIRCUITO CERRADO TV - CCTV'),
    ('7kVEzQtdFmAqx21m', 'PPIE', '45', '¿El área quedó libre de residuos, recortes y material sobrante que puedan obstruir el trabajo posterior?', 'Inspección visual', 'CIRCUITO CERRADO TV - CCTV'),
    ('peD8zOuu26wtba73', 'PRE', '1', '¿La zanja está en el trazo del plano y libre de interferencias con otras redes? (registrar cruces en observaciones)', 'Verificación contra plano', 'TRABAJOS EN TERRENO'),
    ('Hdk8JaJgTrQhyCYM', 'PRE', '2', '¿El ancho y la PROFUNDIDAD de la zanja cumplen el detalle, medidos cada tramo? (la profundidad protege la red del tránsito superior)', 'Medición en campo', 'TRABAJOS EN TERRENO'),
    ('XlhERAZuGxPbzXZj', 'PRE', '3', '¿La cama de arena tiene el espesor indicado y está libre de piedras que puedan dañar el ducto?', 'Medición en campo', 'TRABAJOS EN TERRENO'),
    ('kCnfBjKw6zcsWxa0', 'PRE', '4', '¿El diámetro y el recorrido de la tubería corresponden al plano, sin reducciones ni desvíos no autorizados?', 'Medición en campo', 'TRABAJOS EN TERRENO'),
    ('SaBBkAAY8hBC6fHv', 'PRE', '5', '¿La cantidad de tuberías es exactamente la del plano, contadas una a una en el tramo?', 'Medición en campo', 'TRABAJOS EN TERRENO'),
    ('YFWPVNyabqKIRd7S', 'PRE', '6', '¿La separación entre tuberías cumple el detalle, medida en al menos 3 puntos del tramo?', 'Medición en campo', 'TRABAJOS EN TERRENO'),
    ('FGAHrGucbGWmmnZW', 'PRE', '7', '¿Se verificó que pasa la guía por cada ducto ANTES de tapar la zanja?', 'Prueba de funcionamiento', 'TRABAJOS EN TERRENO'),
    ('I9wMddP3NZ0QWF9J', 'PRE', '8', '¿La cinta o malla de advertencia está a la altura del detalle sobre el ducto, medida antes de completar el relleno? (evita el corte accidental en excavaciones futuras)', 'Medición en campo', 'TRABAJOS EN TERRENO'),
    ('WFvfWp7WiY7Bsx7l', 'PRE', '9', '¿El relleno y la compactación se ejecutaron por capas según especificación, sin dañar el ducto?', 'Medición en campo', 'TRABAJOS EN TERRENO'),
    ('NtHSKdFIZbl6SVPv', 'PRE', '10', '¿El área quedó libre de residuos, recortes y material sobrante que puedan obstruir el trabajo posterior?', 'Inspección visual', 'TRABAJOS EN TERRENO'),
    ('TihgI6u8JI6iLQ6j', 'PRE', '11', '¿El diámetro y la cantidad de tuberías que llegan al buzón corresponden al plano, contadas una a una?', 'Medición en campo', 'TRABAJOS EN BUZÓN'),
    ('kzafrHz0M2nJmBrn', 'PRE', '12', '¿La separación entre tuberías cumple el detalle, medida en al menos 3 puntos del tramo?', 'Medición en campo', 'TRABAJOS EN BUZÓN'),
    ('MokUibhS9yvITYQg', 'PRE', '13', '¿Se respeta la distancia mínima entre el NPT y la tubería, medida en el punto más desfavorable del tramo?', 'Medición en campo', 'TRABAJOS EN BUZÓN'),
    ('SPMFyTwB4Aarr9Hs', 'PRE', '14', '¿Las entradas al buzón quedaron selladas para impedir el ingreso de agua o tierra a los ductos?', 'Inspección visual', 'TRABAJOS EN BUZÓN'),
    ('dT1W5K7Sw4mKbJ2B', 'PRE', '15', '¿El sumidero del buzón drena sin empozar, verificado vertiendo agua?', 'Prueba de funcionamiento', 'TRABAJOS EN BUZÓN'),
    ('FT7N5RJs5gQa9bIV', 'PRE', '16', '¿La tapa instalada es de la clase especificada para el tránsito de esa zona y queda enrasada con el nivel de piso?', 'Verificación documental', 'TRABAJOS EN BUZÓN'),
    ('rQNeUg6CKZPDj7AL', 'PRE', '17', '¿El área quedó libre de residuos, recortes y material sobrante que puedan obstruir el trabajo posterior?', 'Inspección visual', 'TRABAJOS EN BUZÓN'),
    ('uYcJDlqBFZ6Zv8KH', 'PRE', '18', '¿El trazo y replanteo de la red colgada fue verificado topográficamente, con desviación menor a ±2 cm?', 'Medición topográfica', 'REDES COLGADAS'),
    ('YqWHkPVjfQWkYFvv', 'PRE', '19', '¿El diámetro y la cantidad de tuberías o bandejas corresponden al plano, contadas una a una?', 'Medición en campo', 'REDES COLGADAS'),
    ('CIiUlNGG7GxaE5OE', 'PRE', '20', '¿La separación entre tuberías o bandejas cumple el detalle, medida en al menos 3 puntos?', 'Medición en campo', 'REDES COLGADAS'),
    ('v3GDLw0pcJar0iEN', 'PRE', '21', '¿Se respeta la distancia mínima entre el NPT y la tubería o bandeja, medida en el punto más desfavorable?', 'Medición en campo', 'REDES COLGADAS'),
    ('zAmfxJ1MezjtkkfY', 'PRE', '22', '¿Los soportes están al espaciamiento especificado y anclados a elemento estructural, no a falso cielo ni a tabique?', 'Medición en campo', 'REDES COLGADAS'),
    ('HfIlSXlKqmSuvkkF', 'PRE', '23', '¿Se verificó que pasa la guía por cada ducto antes de cerrar el falso cielo?', 'Prueba de funcionamiento', 'REDES COLGADAS'),
    ('sQQsdb3KHqpJFv6a', 'PRE', '24', '¿El área quedó libre de residuos, recortes y material sobrante que puedan obstruir el trabajo posterior?', 'Inspección visual', 'REDES COLGADAS'),
    ('ZVVprWFXOMCQseuv', 'PDA', '1', '¿Los dispositivos están ubicados según el plano? (sensor de temperatura, detector de humo, luz estroboscópica, estación manual y sirena)', 'Verificación contra plano', 'AMBIENTE 1'),
    ('hpag8EgUjFDc8Qfz', 'PDA', '2', '¿La sirena se activa al operar el sensor de temperatura?', 'Prueba de funcionamiento', 'AMBIENTE 1'),
    ('orHcHXAu1lAyXQhQ', 'PDA', '3', '¿La sirena se activa al operar el detector de humo?', 'Prueba de funcionamiento', 'AMBIENTE 1'),
    ('InglDdHSom2K2MWI', 'PDA', '4', '¿El tablero de control reconoce e identifica correctamente el circuito de alarma?', 'Prueba de funcionamiento', 'AMBIENTE 1'),
    ('Wsogtokzc0ilDLot', 'PDA', '5', '¿Los dispositivos están ubicados según el plano? (sensor de temperatura, detector de humo, luz estroboscópica, estación manual y sirena)', 'Verificación contra plano', 'AMBIENTE 2'),
    ('XBcpRk5SYiUIwIyZ', 'PDA', '6', '¿La sirena se activa al operar el sensor de temperatura?', 'Prueba de funcionamiento', 'AMBIENTE 2'),
    ('ZwOhCFblOfS9bkb7', 'PDA', '7', '¿La sirena se activa al operar el detector de humo?', 'Prueba de funcionamiento', 'AMBIENTE 2'),
    ('nyT5FZbdOgW78YoZ', 'PDA', '8', '¿El tablero de control reconoce e identifica correctamente el circuito de alarma?', 'Prueba de funcionamiento', 'AMBIENTE 2'),
    ('qErlnDuiA4ehDHAq', 'PDA', '9', '¿Los dispositivos están ubicados según el plano? (sensor de temperatura, detector de humo, luz estroboscópica, estación manual y sirena)', 'Verificación contra plano', 'AMBIENTE 3'),
    ('BiLjhJN24LZ8Cxo9', 'PDA', '10', '¿La sirena se activa al operar el sensor de temperatura?', 'Prueba de funcionamiento', 'AMBIENTE 3'),
    ('zhS2eNkWMe7K6CQa', 'PDA', '11', '¿La sirena se activa al operar el detector de humo?', 'Prueba de funcionamiento', 'AMBIENTE 3'),
    ('TQvdsxY8zXPvOkmI', 'PDA', '12', '¿El tablero de control reconoce e identifica correctamente el circuito de alarma?', 'Prueba de funcionamiento', 'AMBIENTE 3'),
    ('UH1T0u7yUI1jjMZw', 'PDA', '13', '¿Los dispositivos están ubicados según el plano? (sensor de temperatura, detector de humo, luz estroboscópica, estación manual y sirena)', 'Verificación contra plano', 'AMBIENTE 4'),
    ('m1o3CbYVPgpQm1Ij', 'PDA', '14', '¿La sirena se activa al operar el sensor de temperatura?', 'Prueba de funcionamiento', 'AMBIENTE 4'),
    ('eCqvTq0DlqPcr2hY', 'PDA', '15', '¿La sirena se activa al operar el detector de humo?', 'Prueba de funcionamiento', 'AMBIENTE 4'),
    ('x1r3HAMXuJTaFTM1', 'PDA', '16', '¿El tablero de control reconoce e identifica correctamente el circuito de alarma?', 'Prueba de funcionamiento', 'AMBIENTE 4'),
    ('xKnlg9DCPekkVtR1', 'PDA', '17', '¿Los dispositivos están ubicados según el plano? (sensor de temperatura, detector de humo, luz estroboscópica, estación manual y sirena)', 'Verificación contra plano', 'AMBIENTE 5'),
    ('HEcZ1W2OAmkQqlZW', 'PDA', '18', '¿La sirena se activa al operar el sensor de temperatura?', 'Prueba de funcionamiento', 'AMBIENTE 5'),
    ('mvZ9Vhc7Ryb82WZr', 'PDA', '19', '¿La sirena se activa al operar el detector de humo?', 'Prueba de funcionamiento', 'AMBIENTE 5'),
    ('qlNvut54fnCxnKKA', 'PDA', '20', '¿El tablero de control reconoce e identifica correctamente el circuito de alarma?', 'Prueba de funcionamiento', 'AMBIENTE 5')
),
-- 1) Respaldo del estado actual de las 13 fichas.
respaldo AS (
  INSERT INTO ficha_edit_backups (template_id, project_id, label, operation, snapshot)
  SELECT pt.id, pt.project_id,
         'Antes de v3 — criterio de evaluación real (' || pt.id_protocolo || ')',
         'replace_items_v3',
         jsonb_agg(jsonb_build_object(
           'partida_item', i.partida_item, 'item_description', i.item_description,
           'validation_method', i.validation_method, 'section', i.section
         ) ORDER BY (i.partida_item)::int)
  FROM protocol_templates pt
  JOIN protocol_template_items i ON i.template_id = pt.id
  WHERE pt.project_id = 'mmhYnc2026Unica'
  GROUP BY pt.id, pt.project_id, pt.id_protocolo
  RETURNING 1
),
-- 2) Fuera los ítems viejos (cambia la cantidad de partidas, no solo el texto).
borrados AS (
  DELETE FROM protocol_template_items i
  USING protocol_templates pt
  WHERE pt.project_id = 'mmhYnc2026Unica' AND i.template_id = pt.id
  RETURNING 1
),
-- 3) Ítems v3.
insertados AS (
  INSERT INTO protocol_template_items
    (id, template_id, partida_item, item_description, validation_method, section, created_at, updated_at, org_id)
  SELECT n.id, pt.id, n.partida_item, n.descripcion, n.metodo, n.seccion, 1786000000000, 1786000000000, '11111111-1111-4111-8111-111111111111'
  FROM nuevos n
  JOIN protocol_templates pt
    ON pt.project_id = 'mmhYnc2026Unica' AND pt.id_protocolo = n.id_protocolo
  RETURNING 1
),
-- 4) Tocar las fichas para que móvil y web resincronicen (LWW por updated_at).
touch AS (
  UPDATE protocol_templates SET updated_at = 1786000000000
  WHERE project_id = 'mmhYnc2026Unica'
  RETURNING 1
)
SELECT (SELECT count(*) FROM respaldo)    AS fichas_respaldadas,
       (SELECT count(*) FROM borrados)    AS items_borrados,
       (SELECT count(*) FROM insertados)  AS items_insertados,
       (SELECT count(*) FROM touch)       AS fichas_tocadas;
