-- Mercado Mayorista (mmhYnc2026Unica) — redacción v2 de los ítems.
-- Generado por _genUpdateTextos.js. Solo item_description; validation_method intacto.
WITH nuevos (id_protocolo, partida_item, texto) AS (
  VALUES
    ('CTTR'::text, '1'::text, '¿El trazo lo ejecutó un topógrafo calificado?'::text),
    ('CTTR', '2', '¿El terreno fue liberado y entregado para iniciar el trazo?'),
    ('CTTR', '3', '¿Se verificaron el alineamiento, las medidas y la escuadra del trazo?'),
    ('CTTR', '4', '¿El trazo coincide con el plano base, sin modificaciones? (de haberlas, detallarlas en observaciones)'),
    ('CTTR', '5', '¿Las dimensiones replanteadas de la estructura coinciden con el plano?'),
    ('CTTR', '6', '¿Se materializaron en campo los vértices de la estructura?'),
    ('CTTR', '7', '¿El trazo final de la estructura quedó marcado y verificado?'),
    ('CTTR', '8', '¿El equipo topográfico cuenta con certificado de calibración vigente?'),
    ('CTPT', '1', '¿El levantamiento lo ejecutó un topógrafo calificado?'),
    ('CTPT', '2', '¿El terreno fue liberado y entregado para iniciar el levantamiento?'),
    ('CTPT', '3', '¿Se verificaron el alineamiento, las medidas y la escuadra del levantamiento?'),
    ('CTPT', '4', '¿El levantamiento coincide con el plano base, sin modificaciones? (de haberlas, detallarlas en observaciones)'),
    ('CTPT', '5', '¿Las dimensiones levantadas de la estructura coinciden con el plano?'),
    ('CTPT', '6', '¿Se materializaron en campo los vértices de la estructura?'),
    ('CTPT', '7', '¿El trazo final de la estructura quedó marcado y verificado?'),
    ('CTPT', '8', '¿Los espacios levantados quedaron señalizados en campo?'),
    ('LIPMPP', '1', 'Diámetro de pernos de anclaje'),
    ('LIPMPP', '2', 'Equipo topográfico utilizado'),
    ('LIPMPP', '3', 'N° de serie del equipo'),
    ('LIPMPP', '4', 'Fecha de calibración del equipo'),
    ('LIPMPP', '5', '¿La base de la plancha metálica está correctamente ejecutada?'),
    ('LIPMPP', '6', '¿Los pernos de anclaje tienen la longitud y el diámetro especificados?'),
    ('LIPMPP', '7', '¿La plancha metálica está alineada según el plano?'),
    ('LIPMPP', '8', '¿La plancha metálica y los pernos están nivelados?'),
    ('LIPMPP', '9', '¿La plancha y los pernos de anclaje guardan el alineamiento entre sí?'),
    ('LIPMPP', '10', 'col-[A][Eje / Elemento] // col-[B][Norte (plano)] // col-[C][Este (plano)] // col-[D][Z (plano)] // col-[E][Norte (campo)] // col-[F][Este (campo)] // col-[G][Z (campo)] // col-[H][Var. Norte (m)] // col-[I][Var. Este (m)] // col-[J][Var. Z (m)] // col-[K][Dentro de tolerancia (1=Sí)]'),
    ('LIPMPP', '11', 'Detalle 1'),
    ('LIPMPP', '12', 'Detalle 2'),
    ('LIPMPP', '13', 'Detalle 3'),
    ('LIPMPP', '14', 'Detalle 4'),
    ('LIPMPP', '15', 'Detalle 5'),
    ('PA', '1', '¿Se ejecutó el trabajo conforme al procedimiento aprobado?'),
    ('PA', '2', '¿Se contrastaron los planos de las especialidades y se resolvieron las interferencias? (arquitectura, estructuras e instalaciones)'),
    ('PA', '3', '¿Se realizó la verificación topográfica? (trazo, alineamiento y niveles)'),
    ('PA', '4', '¿Los diámetros del acero corresponden a los detalles del plano?'),
    ('PA', '5', '¿La distribución del acero cumple lo indicado? (cantidad y espaciamiento entre barras)'),
    ('PA', '6', '¿Los empalmes están ubicados donde corresponde? (traslapes según el RNE)'),
    ('PA', '7', '¿El espaciamiento de estribos coincide con los detalles del plano?'),
    ('PA', '8', '¿Las armaduras están correctamente ancladas, fijadas y arriostradas? (mechas, anclajes y arriostres según planos)'),
    ('PA', '9', '¿Las armaduras están limpias y sin defectos? (libres de óxido suelto, rebabas y deformaciones)'),
    ('PA', '10', '¿El frente de trabajo cuenta con las protecciones de seguridad requeridas? (líneas de vida, plataformas de acceso y barandas)'),
    ('PCC', '1', '¿Se ejecutó el trabajo conforme al procedimiento aprobado?'),
    ('PCC', '2', '¿Se verificaron los niveles y el alineamiento antes del vaciado?'),
    ('PCC', '3', '¿Las juntas fueron preparadas y verificadas?'),
    ('PCC', '4', '¿El acero de refuerzo fue liberado?'),
    ('PCC', '5', '¿El encofrado fue liberado?'),
    ('PCC', '6', '¿Las instalaciones sanitarias embebidas fueron verificadas?'),
    ('PCC', '7', '¿Las instalaciones eléctricas embebidas fueron verificadas?'),
    ('PCC', '8', '¿Las instalaciones mecánicas embebidas fueron verificadas?'),
    ('PCC', '9', '¿Los anclajes para estructuras metálicas fueron verificados?'),
    ('PCC', '10', 'N° de batch'),
    ('PCC', '11', 'Tipo de concreto'),
    ('PCC', '12', 'f''c de diseño (kg/cm²)'),
    ('PCC', '13', 'Slump de diseño (pulg)'),
    ('PCC', '14', 'Volumen total (m³)'),
    ('PCC', '15', 'Tipo de colocación'),
    ('PCC', '16', 'Tipo de acabado'),
    ('PCC', '17', 'col-[A][Guía / Batch] // col-[B][Hora inicio] // col-[C][Hora fin] // col-[D][Slump (pulg)] // col-[E][Volumen (m³)] // col-[F][Código de testigos]'),
    ('PCC', '18', 'Batch 1'),
    ('PCC', '19', 'Batch 2'),
    ('PCC', '20', 'Batch 3'),
    ('PCC', '21', 'Batch 4'),
    ('PCC', '22', 'Batch 5'),
    ('PCC', '23', 'Batch 6'),
    ('PCC', '24', 'Volumen total colocado (m³)'),
    ('PCC', '25', '¿El acabado superficial corresponde a lo especificado?'),
    ('PCC', '26', '¿El nivel y el aplomo final del elemento cumplen lo indicado en planos?'),
    ('PCC', '27', '¿Los elementos embebidos quedaron en su posición final correcta?'),
    ('PCC', '28', '¿El área quedó ordenada y limpia tras el vaciado?'),
    ('PCC', '29', '¿Se aplicó el curado especificado? (agua, membrana u otro)'),
    ('PE', '1', '¿Se ejecutó el trabajo conforme al procedimiento aprobado?'),
    ('PE', '2', '¿El trazo y la ubicación del encofrado coinciden con el plano? (ejes, alineamiento, distancias y niveles)'),
    ('PE', '3', '¿El encofrado está alineado, aplomado y sin deformaciones?'),
    ('PE', '4', '¿Se colocaron los dados y separadores laterales que garantizan el recubrimiento?'),
    ('PE', '5', '¿El encofrado está montado, fijado y arriostrado de forma estable?'),
    ('PE', '6', '¿Las dimensiones internas del encofrado corresponden a lo especificado?'),
    ('PE', '7', '¿Se aplicó desmoldante y el interior del encofrado quedó limpio?'),
    ('PE', '8', '¿Están colocados los pases y tubos de instalaciones sanitarias según plano?'),
    ('PE', '9', '¿Están colocados los pases y tubos de instalaciones eléctricas según plano?'),
    ('PE', '10', '¿Se colocaron los soportes y anclajes para los pases e instalaciones varias?'),
    ('PE', '11', '¿El frente de trabajo cuenta con las protecciones de seguridad requeridas?'),
    ('PAA', '1', '¿La varilla quedó alineada y centrada en su posición definitiva?'),
    ('PAA', '2', '¿Se respetó el recubrimiento mínimo de 2 cm respecto al borde del concreto?'),
    ('PAA', '3', '¿La perforación se ejecutó con rotomartillo y broca de carburo para concreto?'),
    ('PAA', '4', '¿El diámetro de la perforación es mayor que el de la varilla, según la ficha técnica del anclaje?'),
    ('PAA', '5', '¿La perforación alcanza al menos 200 mm de profundidad en el concreto estructural?'),
    ('PAA', '6', '¿Se limpió la perforación con aire comprimido y escobilla antes de inyectar?'),
    ('PAA', '7', '¿El adhesivo se inyectó desde el fondo hasta dos tercios del volumen de la perforación?'),
    ('PAA', '8', '¿La varilla se insertó girando hasta el fondo, cubriendo todo el corrugado con resina?'),
    ('PAA', '9', '¿Se respetó el tiempo de curado según la temperatura ambiente? (20 °C: 24 h · 10 °C: 48 h · menos de 5 °C: 72 h)'),
    ('PAA', '10', '¿El frente de trabajo cuenta con las protecciones de seguridad requeridas?'),
    ('PIS', '1', '¿Las tuberías y accesorios se instalaron según el plano?'),
    ('PIS', '2', '¿El material instalado corresponde al especificado? (PVC)'),
    ('PIS', '3', '¿El diámetro de la tubería corresponde al indicado en el plano?'),
    ('PIS', '4', '¿El material está libre de defectos? (fisuras, deformaciones o golpes)'),
    ('PIS', '5', '¿Las tuberías y accesorios están adecuadamente soportados y fijados?'),
    ('PIS', '6', '¿Los terminales expuestos de tubería y las cajas de paso quedaron taponeados?'),
    ('PIE', '1', '¿Los puntos están ubicados según el plano?'),
    ('PIE', '2', '¿Las tuberías están libres de aplastamientos, roturas o dobleces que reduzcan su diámetro interior?'),
    ('PIE', '3', '¿Los accesorios son del mismo material y clase que la tubería? (uniones, conectores y curvas en PVC)'),
    ('PIE', '4', '¿Las cajas se colocaron según el trazo topográfico? (octogonales, rectangulares y de paso)'),
    ('PIE', '5', '¿Las tuberías y accesorios están adecuadamente soportados y fijados?'),
    ('PIE', '6', '¿El área de trabajo quedó limpia y ordenada?'),
    ('PIE', '7', '¿El diámetro de la tubería corresponde al indicado en el plano?'),
    ('PIE', '8', '¿Las tuberías y accesorios están en buen estado?'),
    ('PPIS', '1', '¿La red instalada corresponde al tipo previsto? (agua fría o agua caliente)'),
    ('PPIS', '2', '¿El material de la red corresponde al especificado? (PVC, PPR o acero)'),
    ('PPIS', '3', '¿Los puntos de agua están ubicados según el plano?'),
    ('PPIS', '4', '¿La cantidad de puntos de salida coincide con el plano?'),
    ('PPIS', '5', '¿El diámetro y el recorrido de la tubería corresponden al plano?'),
    ('PPIS', '6', '¿El tipo de salida corresponde al aparato previsto? (ovalín, inodoro u otro)'),
    ('PPIS', '7', '¿Se instaló la válvula de paso donde indica el plano?'),
    ('PPIS', '8', '¿El área de trabajo quedó limpia y ordenada?'),
    ('PPIS', '9', '¿Los puntos de desagüe están ubicados según el plano?'),
    ('PPIS', '10', '¿El material de la red corresponde al especificado? (PVC o PPR)'),
    ('PPIS', '11', '¿La cantidad de puntos de salida coincide con el plano?'),
    ('PPIS', '12', '¿El diámetro y el recorrido de la tubería corresponden al plano?'),
    ('PPIS', '13', '¿El tipo de salida corresponde al aparato previsto? (ovalín, inodoro u otro)'),
    ('PPIS', '14', '¿Se instalaron los puntos de urinario, registro y sumidero previstos?'),
    ('PPIS', '15', '¿El área de trabajo quedó limpia y ordenada?'),
    ('PPIS', '16', '¿Los puntos de ventilación están ubicados según el plano?'),
    ('PPIS', '17', '¿El material de la red corresponde al especificado? (PVC o PPR)'),
    ('PPIS', '18', '¿La cantidad de puntos de salida coincide con el plano?'),
    ('PPIS', '19', '¿El diámetro y el recorrido de la tubería corresponden al plano?'),
    ('PPIS', '20', '¿El área de trabajo quedó limpia y ordenada?'),
    ('PPIE', '1', '¿La caja equipotencial y las cajas de paso están ubicadas según el plano?'),
    ('PPIE', '2', '¿El diámetro, el recorrido de la tubería, la caja y la altura corresponden al plano?'),
    ('PPIE', '3', '¿La cantidad de puntos de salida coincide con el plano?'),
    ('PPIE', '4', '¿El área de trabajo quedó limpia y ordenada?'),
    ('PPIE', '5', '¿Los puntos están ubicados según el plano?'),
    ('PPIE', '6', '¿El diámetro, el recorrido de la tubería, la caja y la altura corresponden al plano?'),
    ('PPIE', '7', '¿La cantidad de puntos de salida coincide con el plano?'),
    ('PPIE', '8', '¿El área de trabajo quedó limpia y ordenada?'),
    ('PPIE', '9', '¿Los puntos están ubicados según el plano?'),
    ('PPIE', '10', '¿El diámetro, el recorrido de la tubería, la caja y la altura corresponden al plano?'),
    ('PPIE', '11', '¿La cantidad de puntos de salida coincide con el plano?'),
    ('PPIE', '12', '¿El área de trabajo quedó limpia y ordenada?'),
    ('PPIE', '13', '¿Los puntos están ubicados según el plano?'),
    ('PPIE', '14', '¿El diámetro, el recorrido de la tubería, la caja y la altura corresponden al plano?'),
    ('PPIE', '15', '¿La cantidad de puntos de salida coincide con el plano?'),
    ('PPIE', '16', '¿El área de trabajo quedó limpia y ordenada?'),
    ('PPIE', '17', '¿Los puntos están ubicados según el plano?'),
    ('PPIE', '18', '¿El diámetro, el recorrido de la tubería, la caja y la altura corresponden al plano?'),
    ('PPIE', '19', '¿La cantidad de puntos de salida coincide con el plano?'),
    ('PPIE', '20', '¿El área de trabajo quedó limpia y ordenada?'),
    ('PPIE', '21', '¿Los puntos están ubicados según el plano? (ACI y plano de intrusión)'),
    ('PPIE', '22', '¿El diámetro, el recorrido de la tubería, la caja y la altura corresponden al plano?'),
    ('PPIE', '23', '¿La cantidad de puntos de salida coincide con el plano?'),
    ('PPIE', '24', '¿El área de trabajo quedó limpia y ordenada?'),
    ('PPIE', '25', '¿Los puntos están ubicados según el plano?'),
    ('PPIE', '26', '¿El diámetro, el recorrido de la tubería, la caja y la altura corresponden al plano?'),
    ('PPIE', '27', '¿La cantidad de puntos de salida coincide con el plano?'),
    ('PPIE', '28', '¿El área de trabajo quedó limpia y ordenada?'),
    ('PPIE', '29', '¿Los puntos están ubicados según el plano?'),
    ('PPIE', '30', '¿El diámetro, el recorrido de la tubería, la caja y la altura corresponden al plano?'),
    ('PPIE', '31', '¿La cantidad de puntos de salida coincide con el plano?'),
    ('PPIE', '32', '¿El área de trabajo quedó limpia y ordenada?'),
    ('PPIE', '33', '¿Los puntos están ubicados según el plano?'),
    ('PPIE', '34', '¿El diámetro, el recorrido de la tubería, la caja y la altura corresponden al plano?'),
    ('PPIE', '35', '¿La cantidad de puntos de salida coincide con el plano?'),
    ('PPIE', '36', '¿El área de trabajo quedó limpia y ordenada?'),
    ('PRE', '1', '¿La zanja está ubicada según el plano?'),
    ('PRE', '2', '¿Las dimensiones de corte de la zanja cumplen el detalle? (ancho y profundidad)'),
    ('PRE', '3', '¿La cama de arena tiene la altura indicada en el detalle?'),
    ('PRE', '4', '¿El diámetro y el recorrido de la tubería corresponden al plano?'),
    ('PRE', '5', '¿La cantidad de tuberías coincide con el plano?'),
    ('PRE', '6', '¿La separación entre tuberías cumple el detalle?'),
    ('PRE', '7', '¿Se colocó la señalización de la red según el detalle? (cinta o malla de advertencia)'),
    ('PRE', '8', '¿El área de trabajo quedó limpia y ordenada?'),
    ('PRE', '9', '¿El diámetro de la tubería que llega al buzón corresponde al plano?'),
    ('PRE', '10', '¿La cantidad de tuberías coincide con el plano?'),
    ('PRE', '11', '¿La separación entre tuberías cumple el detalle?'),
    ('PRE', '12', '¿Se respeta la distancia mínima entre el NPT y la tubería?'),
    ('PRE', '13', '¿El sumidero del buzón se ejecutó según el detalle?'),
    ('PRE', '14', '¿El área de trabajo quedó limpia y ordenada?'),
    ('PRE', '15', '¿El trazo y replanteo de la red colgada fue verificado?'),
    ('PRE', '16', '¿El diámetro de la tubería o bandeja corresponde al plano?'),
    ('PRE', '17', '¿La cantidad de tuberías o bandejas coincide con el plano?'),
    ('PRE', '18', '¿La separación entre tuberías o bandejas cumple el detalle?'),
    ('PRE', '19', '¿Se respeta la distancia mínima entre el NPT y la tubería o bandeja?'),
    ('PRE', '20', '¿El área de trabajo quedó limpia y ordenada?'),
    ('PDA', '1', '¿Los dispositivos están ubicados según el plano? (sensor de temperatura, detector de humo, luz estroboscópica, estación manual y sirena)'),
    ('PDA', '2', '¿La sirena se activa al operar el sensor de temperatura?'),
    ('PDA', '3', '¿La sirena se activa al operar el detector de humo?'),
    ('PDA', '4', '¿El tablero de control reconoce e identifica correctamente el circuito de alarma?'),
    ('PDA', '5', '¿Los dispositivos están ubicados según el plano? (sensor de temperatura, detector de humo, luz estroboscópica, estación manual y sirena)'),
    ('PDA', '6', '¿La sirena se activa al operar el sensor de temperatura?'),
    ('PDA', '7', '¿La sirena se activa al operar el detector de humo?'),
    ('PDA', '8', '¿El tablero de control reconoce e identifica correctamente el circuito de alarma?'),
    ('PDA', '9', '¿Los dispositivos están ubicados según el plano? (sensor de temperatura, detector de humo, luz estroboscópica, estación manual y sirena)'),
    ('PDA', '10', '¿La sirena se activa al operar el sensor de temperatura?'),
    ('PDA', '11', '¿La sirena se activa al operar el detector de humo?'),
    ('PDA', '12', '¿El tablero de control reconoce e identifica correctamente el circuito de alarma?'),
    ('PDA', '13', '¿Los dispositivos están ubicados según el plano? (sensor de temperatura, detector de humo, luz estroboscópica, estación manual y sirena)'),
    ('PDA', '14', '¿La sirena se activa al operar el sensor de temperatura?'),
    ('PDA', '15', '¿La sirena se activa al operar el detector de humo?'),
    ('PDA', '16', '¿El tablero de control reconoce e identifica correctamente el circuito de alarma?'),
    ('PDA', '17', '¿Los dispositivos están ubicados según el plano? (sensor de temperatura, detector de humo, luz estroboscópica, estación manual y sirena)'),
    ('PDA', '18', '¿La sirena se activa al operar el sensor de temperatura?'),
    ('PDA', '19', '¿La sirena se activa al operar el detector de humo?'),
    ('PDA', '20', '¿El tablero de control reconoce e identifica correctamente el circuito de alarma?')
),
-- Respaldo del estado ACTUAL de las 13 fichas antes de tocar nada.
respaldo AS (
  INSERT INTO ficha_edit_backups (template_id, project_id, label, operation, snapshot)
  SELECT pt.id, pt.project_id,
         'Redacción v2 — preguntas reales (' || pt.id_protocolo || ')',
         'update_item_description',
         jsonb_agg(jsonb_build_object(
           'id', i.id, 'partida_item', i.partida_item,
           'item_description', i.item_description,
           'validation_method', i.validation_method, 'section', i.section
         ) ORDER BY (i.partida_item)::int)
  FROM protocol_templates pt
  JOIN protocol_template_items i ON i.template_id = pt.id
  WHERE pt.project_id = 'mmhYnc2026Unica'
  GROUP BY pt.id, pt.project_id, pt.id_protocolo
  RETURNING 1
),
-- Plantillas.
upd_plantilla AS (
  UPDATE protocol_template_items t
  SET item_description = n.texto, updated_at = 1785900000000
  FROM nuevos n, protocol_templates pt
  WHERE pt.project_id = 'mmhYnc2026Unica'
    AND pt.id_protocolo = n.id_protocolo
    AND t.template_id = pt.id
    AND t.partida_item = n.partida_item
    AND t.item_description IS DISTINCT FROM n.texto
  RETURNING 1
),
-- Instancias NO aprobadas (los ensayos ya creados siguen el texto nuevo).
-- Las aprobadas jamás se tocan: son registro firmado.
upd_instancia AS (
  UPDATE protocol_items pi
  SET item_description = n.texto, updated_at = 1785900000000
  FROM nuevos n, protocol_templates pt, protocols p
  WHERE pt.project_id = 'mmhYnc2026Unica'
    AND pt.id_protocolo = n.id_protocolo
    AND p.template_id = pt.id
    AND p.status = 'DRAFT'
    AND pi.protocol_id = p.id
    AND pi.partida_item = n.partida_item
    AND pi.item_description IS DISTINCT FROM n.texto
  RETURNING 1
),
-- Tocar las fichas para que móvil y web se sincronicen (LWW por updated_at).
touch AS (
  UPDATE protocol_templates SET updated_at = 1785900000000
  WHERE project_id = 'mmhYnc2026Unica'
  RETURNING 1
)
SELECT (SELECT count(*) FROM respaldo)      AS fichas_respaldadas,
       (SELECT count(*) FROM upd_plantilla) AS items_plantilla,
       (SELECT count(*) FROM upd_instancia) AS items_instancia,
       (SELECT count(*) FROM touch)         AS fichas_tocadas;
